version: '3'
services:
  react-app-2:
    # build: .
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=MyReactAppProd
    ports:
      - "8080:80"
    # env_file:
    #   - ./.env
