name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Docker production
    runs-on: ubuntu-latest

    steps:
    - name: set env
      run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Build and push Docker image

      run: docker-compose -f docker-compose.yml -f docker-compose-prod.yml build
    - name: Push Docker image
      run: docker-compose push ramyakavi/react-docker-app-2:${{ env.NOW }}



